language: python

git:
  depth: 5000

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install codecov
  - pip install --only-binary=numpy,scipy numpy
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
  - make tests
  - codecov
