language: python

git:
  depth: 5000

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install codecov
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
  - pip install -e .

addons:
  sonarqube:
    organization: "xppackp2o895tua4ki8o3g" # the key of the org you chose at step #3

# command to run tests
script:
  - make tests
  - codecov
  - sonar-scanner
